// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/agent.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 心跳报文
type Heartbeat struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	HeartbeatTime        string   `protobuf:"bytes,2,opt,name=heartbeatTime,proto3" json:"heartbeatTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_3305a4287f8287e0, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Heartbeat) GetHeartbeatTime() string {
	if m != nil {
		return m.HeartbeatTime
	}
	return ""
}

// 主机收集报文
type Collect struct {
	Uptime               string   `protobuf:"bytes,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Cpuarch              string   `protobuf:"bytes,2,opt,name=cpuarch,proto3" json:"cpuarch,omitempty"`
	Cpunum               int32    `protobuf:"varint,3,opt,name=cpunum,proto3" json:"cpunum,omitempty"`
	Memtotal             string   `protobuf:"bytes,4,opt,name=memtotal,proto3" json:"memtotal,omitempty"`
	ColTime              string   `protobuf:"bytes,5,opt,name=ColTime,proto3" json:"ColTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collect) Reset()         { *m = Collect{} }
func (m *Collect) String() string { return proto.CompactTextString(m) }
func (*Collect) ProtoMessage()    {}
func (*Collect) Descriptor() ([]byte, []int) {
	return fileDescriptor_3305a4287f8287e0, []int{1}
}

func (m *Collect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collect.Unmarshal(m, b)
}
func (m *Collect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collect.Marshal(b, m, deterministic)
}
func (m *Collect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collect.Merge(m, src)
}
func (m *Collect) XXX_Size() int {
	return xxx_messageInfo_Collect.Size(m)
}
func (m *Collect) XXX_DiscardUnknown() {
	xxx_messageInfo_Collect.DiscardUnknown(m)
}

var xxx_messageInfo_Collect proto.InternalMessageInfo

func (m *Collect) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *Collect) GetCpuarch() string {
	if m != nil {
		return m.Cpuarch
	}
	return ""
}

func (m *Collect) GetCpunum() int32 {
	if m != nil {
		return m.Cpunum
	}
	return 0
}

func (m *Collect) GetMemtotal() string {
	if m != nil {
		return m.Memtotal
	}
	return ""
}

func (m *Collect) GetColTime() string {
	if m != nil {
		return m.ColTime
	}
	return ""
}

// 主机RPM信息
type Rpms struct {
	Rpmlist              []string `protobuf:"bytes,1,rep,name=rpmlist,proto3" json:"rpmlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rpms) Reset()         { *m = Rpms{} }
func (m *Rpms) String() string { return proto.CompactTextString(m) }
func (*Rpms) ProtoMessage()    {}
func (*Rpms) Descriptor() ([]byte, []int) {
	return fileDescriptor_3305a4287f8287e0, []int{2}
}

func (m *Rpms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rpms.Unmarshal(m, b)
}
func (m *Rpms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rpms.Marshal(b, m, deterministic)
}
func (m *Rpms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rpms.Merge(m, src)
}
func (m *Rpms) XXX_Size() int {
	return xxx_messageInfo_Rpms.Size(m)
}
func (m *Rpms) XXX_DiscardUnknown() {
	xxx_messageInfo_Rpms.DiscardUnknown(m)
}

var xxx_messageInfo_Rpms proto.InternalMessageInfo

func (m *Rpms) GetRpmlist() []string {
	if m != nil {
		return m.Rpmlist
	}
	return nil
}

// 服务端发送更新Agent指令
type UpdateMsg struct {
	Updateswitch         bool     `protobuf:"varint,1,opt,name=updateswitch,proto3" json:"updateswitch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMsg) Reset()         { *m = UpdateMsg{} }
func (m *UpdateMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateMsg) ProtoMessage()    {}
func (*UpdateMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_3305a4287f8287e0, []int{3}
}

func (m *UpdateMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMsg.Unmarshal(m, b)
}
func (m *UpdateMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMsg.Marshal(b, m, deterministic)
}
func (m *UpdateMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMsg.Merge(m, src)
}
func (m *UpdateMsg) XXX_Size() int {
	return xxx_messageInfo_UpdateMsg.Size(m)
}
func (m *UpdateMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMsg proto.InternalMessageInfo

func (m *UpdateMsg) GetUpdateswitch() bool {
	if m != nil {
		return m.Updateswitch
	}
	return false
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "msg.Heartbeat")
	proto.RegisterType((*Collect)(nil), "msg.Collect")
	proto.RegisterType((*Rpms)(nil), "msg.Rpms")
	proto.RegisterType((*UpdateMsg)(nil), "msg.UpdateMsg")
}

func init() { proto.RegisterFile("protobuf/agent.proto", fileDescriptor_3305a4287f8287e0) }

var fileDescriptor_3305a4287f8287e0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xbf, 0x4e, 0x04, 0x21,
	0x10, 0x06, 0xf0, 0xe0, 0xde, 0xbf, 0x9d, 0x68, 0x43, 0x8c, 0x21, 0x56, 0x1b, 0x62, 0x71, 0x95,
	0x57, 0xf8, 0x08, 0xd7, 0x68, 0x61, 0x43, 0xf4, 0x01, 0x58, 0xc4, 0xdd, 0x4d, 0xe0, 0x20, 0x30,
	0xc4, 0x67, 0xf0, 0xad, 0x0d, 0x73, 0x9c, 0xc9, 0x95, 0xbf, 0xe1, 0x9b, 0x2f, 0x13, 0xe0, 0x3e,
	0xa6, 0x80, 0x61, 0x2c, 0xdf, 0x07, 0x3d, 0xd9, 0x13, 0x3e, 0x13, 0x79, 0xe7, 0xf3, 0x24, 0xdf,
	0xa0, 0x7f, 0xb5, 0x3a, 0xe1, 0x68, 0x35, 0xf2, 0x07, 0xd8, 0x64, 0xd4, 0x58, 0xb2, 0x60, 0x03,
	0xdb, 0xf7, 0xaa, 0x89, 0x3f, 0xc1, 0xdd, 0x7c, 0x09, 0x7d, 0x2c, 0xde, 0x8a, 0x1b, 0x7a, 0xbe,
	0x1e, 0xca, 0x5f, 0x06, 0xdb, 0x63, 0x70, 0xce, 0x1a, 0x6a, 0x2a, 0x11, 0x6b, 0xb4, 0x35, 0x9d,
	0xc5, 0x05, 0x6c, 0x4d, 0x2c, 0x3a, 0x99, 0xb9, 0x75, 0x5c, 0x58, 0x37, 0x4c, 0x2c, 0xa7, 0xe2,
	0x45, 0x37, 0xb0, 0xfd, 0x5a, 0x35, 0xf1, 0x47, 0xd8, 0x79, 0xeb, 0x31, 0xa0, 0x76, 0x62, 0x45,
	0x2b, 0xff, 0xae, 0x6d, 0xc7, 0xe0, 0xe8, 0xa2, 0xf5, 0xb9, 0xad, 0x51, 0x0e, 0xb0, 0x52, 0xd1,
	0xe7, 0x9a, 0x48, 0xd1, 0xbb, 0x25, 0xa3, 0x60, 0x43, 0x57, 0x13, 0x8d, 0xf2, 0x00, 0xfd, 0x67,
	0xfc, 0xd2, 0x68, 0xdf, 0xf3, 0xc4, 0x25, 0xdc, 0x16, 0x42, 0xfe, 0x59, 0xd0, 0xcc, 0x74, 0xf4,
	0x4e, 0x5d, 0xcd, 0xc6, 0x0d, 0xfd, 0xda, 0xcb, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x96,
	0x95, 0xf6, 0x4d, 0x01, 0x00, 0x00,
}
